
spring:
  h2:
    console:
      enabled: true
    serverPort: 9092
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.0.103:5432/postgres
    username: postgres
    password: postgres
    maxActive: 30
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    hibernate:
      ddl-auto: none

    properties:
      javax:
        persistence:
          validation:
            mode: none
javax:
  persistence:
    validation:
      mode: NONE

#    hibernate:
#      ddl-auto: update
